# Generated by Django 4.2.26 on 2025-11-28 17:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='应用名称')),
                ('version', models.CharField(max_length=50, verbose_name='版本')),
                ('description', models.TextField(blank=True, verbose_name='应用描述')),
                ('owner', models.CharField(blank=True, max_length=100, verbose_name='应用负责人')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '应用',
                'verbose_name_plural': '应用管理',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='部门名称')),
                ('manager', models.CharField(blank=True, max_length=100, verbose_name='负责人')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='联系方式')),
                ('description', models.TextField(blank=True, verbose_name='部门描述')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='cmdb_core.department', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门管理',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='服务器名称')),
                ('hostname', models.CharField(max_length=255, unique=True, verbose_name='主机名')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP地址')),
                ('os_type', models.CharField(max_length=50, verbose_name='操作系统类型')),
                ('os_version', models.CharField(max_length=50, verbose_name='操作系统版本')),
                ('cpu', models.CharField(max_length=50, verbose_name='CPU信息')),
                ('memory', models.CharField(max_length=50, verbose_name='内存信息')),
                ('disk', models.CharField(max_length=100, verbose_name='磁盘信息')),
                ('status', models.CharField(choices=[('running', '运行中'), ('stopped', '已停止'), ('maintenance', '维护中'), ('fault', '故障')], default='running', max_length=20, verbose_name='服务器状态')),
                ('administrator', models.CharField(blank=True, max_length=100, verbose_name='管理员')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='物理位置')),
                ('description', models.TextField(blank=True, verbose_name='服务器描述')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb_core.department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '服务器',
                'verbose_name_plural': '服务器管理',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='服务名称')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='服务端口')),
                ('status', models.CharField(choices=[('running', '运行中'), ('stopped', '已停止'), ('maintenance', '维护中'), ('deploying', '部署中')], default='running', max_length=20, verbose_name='服务状态')),
                ('description', models.TextField(blank=True, verbose_name='服务描述')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb_core.application', verbose_name='所属应用')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb_core.server', verbose_name='部署服务器')),
            ],
            options={
                'verbose_name': '服务',
                'verbose_name_plural': '服务管理',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_object_id', models.PositiveIntegerField()),
                ('target_object_id', models.PositiveIntegerField()),
                ('relationship_type', models.CharField(choices=[('depends_on', '依赖'), ('hosts', '部署于'), ('connects_to', '连接到'), ('belongs_to', '属于'), ('manages', '管理')], max_length=20, verbose_name='关系类型')),
                ('description', models.TextField(blank=True, verbose_name='关系描述')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('source_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_relationships', to='contenttypes.contenttype')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_relationships', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': '资源关系',
                'verbose_name_plural': '资源关系管理',
            },
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('device_type', models.CharField(choices=[('switch', '交换机'), ('router', '路由器'), ('firewall', '防火墙'), ('loadbalancer', '负载均衡器'), ('other', '其他')], max_length=20, verbose_name='设备类型')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='管理IP')),
                ('vendor', models.CharField(max_length=50, verbose_name='厂商')),
                ('model', models.CharField(max_length=50, verbose_name='型号')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='序列号')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='物理位置')),
                ('administrator', models.CharField(blank=True, max_length=100, verbose_name='管理员')),
                ('description', models.TextField(blank=True, verbose_name='设备描述')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb_core.department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '网络设备',
                'verbose_name_plural': '网络设备管理',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb_core.department', verbose_name='所属部门'),
        ),
    ]
