# Generated by Django 4.2.26 on 2025-11-28 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, verbose_name='模板描述')),
                ('created_by', models.CharField(default='admin', max_length=100, verbose_name='创建人')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '集群模板',
                'verbose_name_plural': '集群模板管理',
            },
        ),
    ]
